AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters: 
  pRole:
    Type: String
    #Default: av-dmro-glue-service-role
    Default: AWSGlueServiceRole-glue-role
    Description: "IAM role that is used for Glue Job"
  pDatabaseName:
    Type: String
    Default: av-dmro-sap-aurora
    Description: "Database used for clue catelog"

  ps3scriptpath:
    Type: String
    Default: "s3://av-dmro-glue-458793/samplescript.py"
    Description: "script location of glue-job script file"
  pRoleArn:
    Type: String
    Default: av-dmro-glue-service-role
    Description: "Role ARN to create Glue Crawler"
  JDBCConnection:
    Type: String 
    Default: av-dmro-sap-test-1
    Description: "Connection name used for sap database"
  JDBCPath:
    Type: String
    Default: dmro_materials_dev/public/gea_onhand_materials_hana
    Description: "Database path"


  


# Resources section defines metadata for the Data Catalog
Resources:
# Create an AWS Glue database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      # The database is created in the Data Catalog for your account
      CatalogId: !Ref AWS::AccountId   
      DatabaseInput:
        # The name of the database is defined in the Parameters section above
        Name: !Ref pDatabaseName	
        Description: Database to hold tables for flights data

  GlueJob:
    Type: AWS::Glue::Job
    Properties: 
      Command: 
        "Name": "gluejobscript"
        "ScriptLocation": !Ref ps3scriptpath
        #"extra-jars": s3://ngdbc.jar"
      Connections: 
      #  - av-dmro-sap-test1
        - connection-1
      DefaultArguments: {
        "--additional-python-modules": !Sub "pg8000,pyarrow==2,awswrangler",
        "--class": !Sub "GlueApp"
      }
      Description: Description for glue-job
      GlueVersion: 3.0
      MaxRetries: 2
      Name: av-dmro-glue-job
      NumberOfWorkers: 5
      Role: !Ref pRole
      #SecurityConfiguration: String
      WorkerType: G.1X
  
  
  DataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "DataCrawler"
      Description: "Creates Data Crawler for Data"
      DatabaseName: !Ref pDatabaseName
      #Role: !GetAtt pRole.Arn # Required
      SchemaChangePolicy:
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      TablePrefix: sap_
      Targets:
        JdbcTargets:
          - ConnectionName: ! Ref JDBCConnection
          - Path: !Ref JDBCPath
    