AWSTemplateFormatVersion: 2010-09-09
Description: Working with custom resources and S3

Parameters:
  pRole:
    Type: String
    #Default: av-dmro-glue-service-role
    Default: av-dmro-glue-service-role
    Description: "IAM role that is used for Glue Job"
  pDatabaseName:
    Type: String
    Default: av-dmro-sap-aurora
    Description: "Database used for clue catelog"

  ps3scriptpath:
    Type: String
    Default: "s3://av-dmro-glue-458793/samplescript.py"
    Description: "script location of glue-job script file"
  pRoleArn:
    Type: String
    Default: arn:aws:iam::978671394047:role/av-dmro-glue-service-role
    Description: "Role ARN to create Glue Crawler"
  JDBCConnection:
    Type: String 
    Default: av-dmro-sap-test-1
    Description: "Connection name used for sap database"
  JDBCPath:
    Type: String
    Default: dmro_materials_dev/public/gea_onhand_materials_hana
    Description: "Database path"
  S3BucketName:
    Type: String
    Description: "S3 bucket to create."
    Default: "av-dmro-glue52465872"
  lambdaexecutionroleArn:
    Type: String
    Default: arn:aws:iam::978671394047:role/av-dmro-lambdaexecution_role
  WorkflowName:
    Type: String
    Description: A data processing pipeline that is comprised of a crawler, jobs, and triggers. This workflow converts uploaded data files into Apache Parquet format.
    Default: av-dmro-s3trigger_data_conversion_workflow

  DatabaseName:
    Type: String
    Description: The AWS Glue Data Catalog database that is used to hold the tables created in this walkthrough.
    Default: event_driven_workflow_tutorial

  TableName:
    Type: String
    Description: The Data Catalog table representing the Parquet files being converted by the workflow.
    Default: products
Resources:

  MyCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt crawlertrigger.Arn
      FunctionName: "Crawler-TriggerFunction"


  EventBridgeRule:
    #DependsOn:
      #- av-dmro-glue-service-role
      #- EventDrivenWorkflow
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub glue_Crawler_trigger_rule-${AWS::StackName}
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - glue.amazonaws.com
          eventName:
            - CreateCrawler
          requestParameters:
            name: av-dmro-console
      Targets:
        -
          Arn: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:Crawler/av-dmro-console
          Id: CloudTrailTriggersWorkflow
          RoleArn: !Ref pRoleArn



  

 

